#!/bin/bash
#
# This script creates the ucosii_net_zipfs Board Support Package (BSP).

BSP_TYPE=ucosii
BSP_DIR=.
SOPC_DIR=../../..

# Run nios2-bsp utility to create a HAL BSP in this directory
# for the system with a .sopc file in $SOPC_DIR.
cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_DIR --cmd enable_sw_package altera_ro_zipfs --cmd enable_sw_package altera_iniche --set altera_iniche.iniche_default_if lan91c111 $@"

echo "create-this-bsp: Running \"$cmd\""
$cmd || {
    echo "$cmd failed"
    exit 1
}

echo "create-this-bsp: Running make"
make
