project_open -current_revision $quartus(args)

# Analysis & Synthesis Assignments
# ================================
set_global_assignment -name FAMILY Stratix

# Fitter Assignments
# ==================
set_global_assignment -name DEVICE EP1S10F780C6

# Pin & Location Assignments
# ==========================
set_location_assignment PIN_Y27 -to CTS[1]
set_location_assignment PIN_AA27 -to CTS[2]
set_location_assignment PIN_Y25 -to DCD[1]
set_location_assignment PIN_AA26 -to DCD[2]
set_location_assignment PIN_Y26 -to DSR[1]
set_location_assignment PIN_AA25 -to DSR[2]
set_location_assignment PIN_V19 -to DTR[1]
set_location_assignment PIN_V22 -to DTR[2]
set_location_assignment PIN_C21 -to out_port_from_the_seven_seg_pio[0]
set_location_assignment PIN_B19 -to out_port_from_the_seven_seg_pio[10]
set_location_assignment PIN_A19 -to out_port_from_the_seven_seg_pio[11]
set_location_assignment PIN_D18 -to out_port_from_the_seven_seg_pio[12]
set_location_assignment PIN_C18 -to out_port_from_the_seven_seg_pio[13]
set_location_assignment PIN_A18 -to out_port_from_the_seven_seg_pio[14]
set_location_assignment PIN_D19 -to out_port_from_the_seven_seg_pio[15]
set_location_assignment PIN_B21 -to out_port_from_the_seven_seg_pio[1]
set_location_assignment PIN_A21 -to out_port_from_the_seven_seg_pio[2]
set_location_assignment PIN_C20 -to out_port_from_the_seven_seg_pio[3]
set_location_assignment PIN_A20 -to out_port_from_the_seven_seg_pio[4]
set_location_assignment PIN_B20 -to out_port_from_the_seven_seg_pio[5]
set_location_assignment PIN_B18 -to out_port_from_the_seven_seg_pio[6]
set_location_assignment PIN_D21 -to out_port_from_the_seven_seg_pio[7]
set_location_assignment PIN_E19 -to out_port_from_the_seven_seg_pio[8]
set_location_assignment PIN_C19 -to out_port_from_the_seven_seg_pio[9]
set_location_assignment PIN_V25 -to ENET_ADS_N
set_location_assignment PIN_V28 -to ENET_AEN
set_location_assignment PIN_T22 -to byteenablen_to_the_lan91c111[0]
set_location_assignment PIN_U26 -to byteenablen_to_the_lan91c111[1]
set_location_assignment PIN_U25 -to byteenablen_to_the_lan91c111[2]
set_location_assignment PIN_T19 -to byteenablen_to_the_lan91c111[3]
set_location_assignment PIN_U27 -to ENET_CYCLE_N
set_location_assignment PIN_T20 -to ENET_DATACS_N
set_location_assignment PIN_V27 -to irq_from_the_lan91c111
set_location_assignment PIN_V26 -to ardy_from_the_lan91c111
set_location_assignment PIN_T23 -to ior_n_to_the_lan91c111
set_location_assignment PIN_T24 -to iow_n_to_the_lan91c111
set_location_assignment PIN_R26 -to ENET_LCLK
set_location_assignment PIN_T26 -to ENET_LDEV_N
set_location_assignment PIN_T28 -to ENET_RDYRTN_N
set_location_assignment PIN_T25 -to ENET_SRDY_N
set_location_assignment PIN_W28 -to ENET_VLBUS_N
set_location_assignment PIN_T21 -to ENET_W_R_N
set_location_assignment PIN_K19 -to select_n_to_the_ext_flash
set_location_assignment PIN_F19 -to read_n_to_the_ext_flash
set_location_assignment PIN_G19 -to write_n_to_the_ext_flash
set_location_assignment PIN_L18 -to FLASH_RY_BY_N
set_location_assignment PIN_A4 -to ext_ram_bus_address[0]
set_location_assignment PIN_A6 -to ext_ram_bus_address[10]
set_location_assignment PIN_B7 -to ext_ram_bus_address[11]
set_location_assignment PIN_D6 -to ext_ram_bus_address[12]
set_location_assignment PIN_A7 -to ext_ram_bus_address[13]
set_location_assignment PIN_D7 -to ext_ram_bus_address[14]
set_location_assignment PIN_C6 -to ext_ram_bus_address[15]
set_location_assignment PIN_C7 -to ext_ram_bus_address[16]
set_location_assignment PIN_B6 -to ext_ram_bus_address[17]
set_location_assignment PIN_D8 -to ext_ram_bus_address[18]
set_location_assignment PIN_C8 -to ext_ram_bus_address[19]
set_location_assignment PIN_A3 -to ext_ram_bus_address[1]
set_location_assignment PIN_E8 -to ext_ram_bus_address[20]
set_location_assignment PIN_D9 -to ext_ram_bus_address[21]
set_location_assignment PIN_B9 -to ext_ram_bus_address[22]
set_location_assignment PIN_B3 -to ext_ram_bus_address[2]
set_location_assignment PIN_B5 -to ext_ram_bus_address[3]
set_location_assignment PIN_B4 -to ext_ram_bus_address[4]
set_location_assignment PIN_C4 -to ext_ram_bus_address[5]
set_location_assignment PIN_A5 -to ext_ram_bus_address[6]
set_location_assignment PIN_C5 -to ext_ram_bus_address[7]
set_location_assignment PIN_D5 -to ext_ram_bus_address[8]
set_location_assignment PIN_E6 -to ext_ram_bus_address[9]
set_location_assignment PIN_H12 -to ext_ram_bus_data[0]
set_location_assignment PIN_A9 -to ext_ram_bus_data[10]
set_location_assignment PIN_C9 -to ext_ram_bus_data[11]
set_location_assignment PIN_E10 -to ext_ram_bus_data[12]
set_location_assignment PIN_A10 -to ext_ram_bus_data[13]
set_location_assignment PIN_C10 -to ext_ram_bus_data[14]
set_location_assignment PIN_B10 -to ext_ram_bus_data[15]
set_location_assignment PIN_A11 -to ext_ram_bus_data[16]
set_location_assignment PIN_C11 -to ext_ram_bus_data[17]
set_location_assignment PIN_D11 -to ext_ram_bus_data[18]
set_location_assignment PIN_B11 -to ext_ram_bus_data[19]
set_location_assignment PIN_F12 -to ext_ram_bus_data[1]
set_location_assignment PIN_D10 -to ext_ram_bus_data[20]
set_location_assignment PIN_G10 -to ext_ram_bus_data[21]
set_location_assignment PIN_F10 -to ext_ram_bus_data[22]
set_location_assignment PIN_H11 -to ext_ram_bus_data[23]
set_location_assignment PIN_G11 -to ext_ram_bus_data[24]
set_location_assignment PIN_F8 -to ext_ram_bus_data[25]
set_location_assignment PIN_J9 -to ext_ram_bus_data[26]
set_location_assignment PIN_J13 -to ext_ram_bus_data[27]
set_location_assignment PIN_L13 -to ext_ram_bus_data[28]
set_location_assignment PIN_M11 -to ext_ram_bus_data[29]
set_location_assignment PIN_J12 -to ext_ram_bus_data[2]
set_location_assignment PIN_L11 -to ext_ram_bus_data[30]
set_location_assignment PIN_G7 -to ext_ram_bus_data[31]
set_location_assignment PIN_M12 -to ext_ram_bus_data[3]
set_location_assignment PIN_H17 -to ext_ram_bus_data[4]
set_location_assignment PIN_K18 -to ext_ram_bus_data[5]
set_location_assignment PIN_H18 -to ext_ram_bus_data[6]
set_location_assignment PIN_G18 -to ext_ram_bus_data[7]
set_location_assignment PIN_B8 -to ext_ram_bus_data[8]
set_location_assignment PIN_A8 -to ext_ram_bus_data[9]
set_location_assignment PIN_W11 -to INIT_DONE
set_location_assignment PIN_H3 -to LCD_data_to_and_from_the_lcd_display[0]
set_location_assignment PIN_K3 -to LCD_E_from_the_lcd_display
set_location_assignment PIN_L7 -to LCD_data_to_and_from_the_lcd_display[1]
set_location_assignment PIN_L8 -to LCD_data_to_and_from_the_lcd_display[2]
set_location_assignment PIN_H2 -to LCD_data_to_and_from_the_lcd_display[3]
set_location_assignment PIN_H1 -to LCD_data_to_and_from_the_lcd_display[4]
set_location_assignment PIN_L6 -to LCD_data_to_and_from_the_lcd_display[5]
set_location_assignment PIN_L5 -to LCD_data_to_and_from_the_lcd_display[6]
set_location_assignment PIN_J4 -to LCD_data_to_and_from_the_lcd_display[7]
set_location_assignment PIN_M8 -to LCD_RW_from_the_lcd_display
set_location_assignment PIN_M7 -to LCD_RS_from_the_lcd_display
set_location_assignment PIN_H27 -to out_port_from_the_led_pio[0]
set_location_assignment PIN_H28 -to out_port_from_the_led_pio[1]
set_location_assignment PIN_L23 -to out_port_from_the_led_pio[2]
set_location_assignment PIN_L24 -to out_port_from_the_led_pio[3]
set_location_assignment PIN_J25 -to out_port_from_the_led_pio[4]
set_location_assignment PIN_J26 -to out_port_from_the_led_pio[5]
set_location_assignment PIN_L20 -to out_port_from_the_led_pio[6]
set_location_assignment PIN_L19 -to out_port_from_the_led_pio[7]
set_location_assignment PIN_H26 -to jtag_debug_offchip_trace_clk_from_the_cpu
set_location_assignment PIN_N24 -to TR_DEBUGACK
set_location_assignment PIN_K22 -to TR_DEBUGREQ
set_location_assignment PIN_N23 -to jtag_debug_trigout_from_the_cpu
set_location_assignment PIN_N25 -to jtag_debug_offchip_trace_data_from_the_cpu[0]
set_location_assignment PIN_N26 -to jtag_debug_offchip_trace_data_from_the_cpu[1]
set_location_assignment PIN_L26 -to jtag_debug_offchip_trace_data_from_the_cpu[2]
set_location_assignment PIN_L25 -to jtag_debug_offchip_trace_data_from_the_cpu[3]
set_location_assignment PIN_M19 -to jtag_debug_offchip_trace_data_from_the_cpu[4]
set_location_assignment PIN_M20 -to jtag_debug_offchip_trace_data_from_the_cpu[5]
set_location_assignment PIN_K28 -to jtag_debug_offchip_trace_data_from_the_cpu[6]
set_location_assignment PIN_K27 -to jtag_debug_offchip_trace_data_from_the_cpu[7]
set_location_assignment PIN_N21 -to jtag_debug_offchip_trace_data_from_the_cpu[8]
set_location_assignment PIN_N22 -to jtag_debug_offchip_trace_data_from_the_cpu[9]
set_location_assignment PIN_M26 -to jtag_debug_offchip_trace_data_from_the_cpu[10]
set_location_assignment PIN_M25 -to jtag_debug_offchip_trace_data_from_the_cpu[11]
set_location_assignment PIN_L28 -to jtag_debug_offchip_trace_data_from_the_cpu[12]
set_location_assignment PIN_L27 -to jtag_debug_offchip_trace_data_from_the_cpu[13]
set_location_assignment PIN_P26 -to jtag_debug_offchip_trace_data_from_the_cpu[14]
set_location_assignment PIN_N19 -to jtag_debug_offchip_trace_data_from_the_cpu[15]
set_location_assignment PIN_N20 -to jtag_debug_offchip_trace_data_from_the_cpu[16]
set_location_assignment PIN_N28 -to jtag_debug_offchip_trace_data_from_the_cpu[17]
set_location_assignment PIN_AC9 -to reset_n
set_location_assignment PIN_R27 -to PLD_CLKFB
set_location_assignment PIN_AC17 -to PLD_CLOCKINPUT[2]
set_location_assignment PIN_U2 -to bidir_port_to_and_from_the_reconfig_request_pio
set_location_assignment PIN_P27 -to PROTO1_CLKOUT
set_location_assignment PIN_L4 -to PROTO1_IO[16]
set_location_assignment PIN_K1 -to PROTO1_IO[19]
set_location_assignment PIN_M5 -to PROTO1_IO[22]
set_location_assignment PIN_K4 -to PROTO1_IO[23]
set_location_assignment PIN_J1 -to PROTO1_IO[28]
set_location_assignment PIN_G2 -to PROTO1_IO[40]
set_location_assignment PIN_AB18 -to PROTO2_CARDSEL_N
set_location_assignment PIN_R4 -to PROTO2_CLKOUT
set_location_assignment PIN_AD19 -to PROTO2_IO[0]
set_location_assignment PIN_AD21 -to PROTO2_IO[10]
set_location_assignment PIN_AG20 -to PROTO2_IO[11]
set_location_assignment PIN_AG22 -to PROTO2_IO[12]
set_location_assignment PIN_AH22 -to PROTO2_IO[13]
set_location_assignment PIN_AF22 -to PROTO2_IO[14]
set_location_assignment PIN_AE22 -to PROTO2_IO[15]
set_location_assignment PIN_AH23 -to PROTO2_IO[16]
set_location_assignment PIN_AF23 -to PROTO2_IO[17]
set_location_assignment PIN_AD23 -to PROTO2_IO[18]
set_location_assignment PIN_AG23 -to PROTO2_IO[19]
set_location_assignment PIN_AE19 -to PROTO2_IO[1]
set_location_assignment PIN_AE23 -to PROTO2_IO[20]
set_location_assignment PIN_AH24 -to PROTO2_IO[21]
set_location_assignment PIN_AE24 -to PROTO2_IO[22]
set_location_assignment PIN_AG24 -to PROTO2_IO[23]
set_location_assignment PIN_AF25 -to PROTO2_IO[24]
set_location_assignment PIN_AH25 -to PROTO2_IO[25]
set_location_assignment PIN_AG25 -to PROTO2_IO[26]
set_location_assignment PIN_AH26 -to PROTO2_IO[27]
set_location_assignment PIN_AG26 -to PROTO2_IO[28]
set_location_assignment PIN_AF24 -to PROTO2_IO[29]
set_location_assignment PIN_AF18 -to PROTO2_IO[2]
set_location_assignment PIN_AC21 -to PROTO2_IO[30]
set_location_assignment PIN_AC19 -to PROTO2_IO[31]
set_location_assignment PIN_AA20 -to PROTO2_IO[32]
set_location_assignment PIN_Y19 -to PROTO2_IO[33]
set_location_assignment PIN_W19 -to PROTO2_IO[34]
set_location_assignment PIN_W18 -to PROTO2_IO[35]
set_location_assignment PIN_AA19 -to PROTO2_IO[36]
set_location_assignment PIN_Y17 -to PROTO2_IO[37]
set_location_assignment PIN_AB17 -to PROTO2_IO[38]
set_location_assignment PIN_AB19 -to PROTO2_IO[39]
set_location_assignment PIN_AH20 -to PROTO2_IO[3]
set_location_assignment PIN_V18 -to PROTO2_IO[40]
set_location_assignment PIN_AH21 -to PROTO2_IO[4]
set_location_assignment PIN_AF20 -to PROTO2_IO[5]
set_location_assignment PIN_AE20 -to PROTO2_IO[6]
set_location_assignment PIN_AF21 -to PROTO2_IO[7]
set_location_assignment PIN_AG21 -to PROTO2_IO[8]
set_location_assignment PIN_AE21 -to PROTO2_IO[9]
set_location_assignment PIN_U22 -to RI[1]
set_location_assignment PIN_V23 -to RI[2]
set_location_assignment PIN_U23 -to RTS[1]
set_location_assignment PIN_V20 -to RTS[2]
set_location_assignment PIN_Y28 -to rxd_to_the_uart1
set_location_assignment PIN_AA28 -to rxd_to_the_uart2
set_location_assignment PIN_AE4 -to zs_addr_from_the_sdram[0]
set_location_assignment PIN_Y11 -to zs_addr_from_the_sdram[10]
set_location_assignment PIN_AB7 -to zs_addr_from_the_sdram[11]
set_location_assignment PIN_W12 -to zs_addr_from_the_sdram[1]
set_location_assignment PIN_AC11 -to zs_addr_from_the_sdram[2]
set_location_assignment PIN_W10 -to zs_addr_from_the_sdram[3]
set_location_assignment PIN_AA11 -to zs_addr_from_the_sdram[4]
set_location_assignment PIN_AC10 -to zs_addr_from_the_sdram[5]
set_location_assignment PIN_AB11 -to zs_addr_from_the_sdram[6]
set_location_assignment PIN_AC8 -to zs_addr_from_the_sdram[7]
set_location_assignment PIN_AB10 -to zs_addr_from_the_sdram[8]
set_location_assignment PIN_V11 -to zs_addr_from_the_sdram[9]
set_location_assignment PIN_AG19 -to zs_ba_from_the_sdram[0]
set_location_assignment PIN_AF19 -to zs_ba_from_the_sdram[1]
set_location_assignment PIN_AD18 -to zs_cas_n_from_the_sdram
set_location_assignment PIN_AE18 -to zs_cke_from_the_sdram
set_location_assignment PIN_AG18 -to zs_cs_n_from_the_sdram
set_location_assignment PIN_AE14 -to zs_dqm_from_the_sdram[0]
set_location_assignment PIN_Y13 -to zs_dqm_from_the_sdram[1]
set_location_assignment PIN_AE7 -to zs_dqm_from_the_sdram[2]
set_location_assignment PIN_AG10 -to zs_dqm_from_the_sdram[3]
set_location_assignment PIN_AH4 -to zs_dq_to_and_from_the_sdram[0]
set_location_assignment PIN_AH6 -to zs_dq_to_and_from_the_sdram[10]
set_location_assignment PIN_AD6 -to zs_dq_to_and_from_the_sdram[11]
set_location_assignment PIN_AF7 -to zs_dq_to_and_from_the_sdram[12]
set_location_assignment PIN_AH7 -to zs_dq_to_and_from_the_sdram[13]
set_location_assignment PIN_AG7 -to zs_dq_to_and_from_the_sdram[14]
set_location_assignment PIN_AF6 -to zs_dq_to_and_from_the_sdram[15]
set_location_assignment PIN_AG8 -to zs_dq_to_and_from_the_sdram[16]
set_location_assignment PIN_AF8 -to zs_dq_to_and_from_the_sdram[17]
set_location_assignment PIN_AD8 -to zs_dq_to_and_from_the_sdram[18]
set_location_assignment PIN_AH9 -to zs_dq_to_and_from_the_sdram[19]
set_location_assignment PIN_AE5 -to zs_dq_to_and_from_the_sdram[1]
set_location_assignment PIN_AH8 -to zs_dq_to_and_from_the_sdram[20]
set_location_assignment PIN_AE9 -to zs_dq_to_and_from_the_sdram[21]
set_location_assignment PIN_AF9 -to zs_dq_to_and_from_the_sdram[22]
set_location_assignment PIN_AG9 -to zs_dq_to_and_from_the_sdram[23]
set_location_assignment PIN_AD10 -to zs_dq_to_and_from_the_sdram[24]
set_location_assignment PIN_AF10 -to zs_dq_to_and_from_the_sdram[25]
set_location_assignment PIN_AH10 -to zs_dq_to_and_from_the_sdram[26]
set_location_assignment PIN_AE10 -to zs_dq_to_and_from_the_sdram[27]
set_location_assignment PIN_AF11 -to zs_dq_to_and_from_the_sdram[28]
set_location_assignment PIN_AE11 -to zs_dq_to_and_from_the_sdram[29]
set_location_assignment PIN_AG3 -to zs_dq_to_and_from_the_sdram[2]
set_location_assignment PIN_AH11 -to zs_dq_to_and_from_the_sdram[30]
set_location_assignment PIN_AG11 -to zs_dq_to_and_from_the_sdram[31]
set_location_assignment PIN_AG5 -to zs_dq_to_and_from_the_sdram[3]
set_location_assignment PIN_AG4 -to zs_dq_to_and_from_the_sdram[4]
set_location_assignment PIN_AF4 -to zs_dq_to_and_from_the_sdram[5]
set_location_assignment PIN_AH5 -to zs_dq_to_and_from_the_sdram[6]
set_location_assignment PIN_AF5 -to zs_dq_to_and_from_the_sdram[7]
set_location_assignment PIN_AE6 -to zs_dq_to_and_from_the_sdram[8]
set_location_assignment PIN_AG6 -to zs_dq_to_and_from_the_sdram[9]
set_location_assignment PIN_AH3 -to zs_ras_n_from_the_sdram
set_location_assignment PIN_AH19 -to zs_we_n_from_the_sdram
set_location_assignment PIN_M18 -to be_n_to_the_ext_ram[0]
set_location_assignment PIN_F17 -to be_n_to_the_ext_ram[1]
set_location_assignment PIN_J18 -to be_n_to_the_ext_ram[2]
set_location_assignment PIN_L17 -to be_n_to_the_ext_ram[3]
set_location_assignment PIN_B24 -to select_n_to_the_ext_ram
set_location_assignment PIN_B26 -to read_n_to_the_ext_ram
set_location_assignment PIN_C24 -to write_n_to_the_ext_ram
set_location_assignment PIN_U21 -to txd_from_the_uart1
set_location_assignment PIN_V24 -to txd_from_the_uart2
set_location_assignment PIN_W5 -to in_port_to_the_button_pio[0]
set_location_assignment PIN_W6 -to in_port_to_the_button_pio[1]
set_location_assignment PIN_AB2 -to in_port_to_the_button_pio[2]
set_location_assignment PIN_AB1 -to in_port_to_the_button_pio[3]
set_location_assignment PIN_R3 -to cf_detect
set_location_assignment PIN_M5 -to cf_intrq
set_location_assignment PIN_K1 -to cf_iordy
set_location_assignment PIN_L9 -to cf_addr[0]
set_location_assignment PIN_J3 -to cf_addr[1]
set_location_assignment PIN_L10 -to cf_addr[2]
set_location_assignment PIN_L6 -to cf_addr[3]
set_location_assignment PIN_H1 -to cf_addr[4]
set_location_assignment PIN_H2 -to cf_addr[5]
set_location_assignment PIN_L8 -to cf_addr[6]
set_location_assignment PIN_L7 -to cf_addr[7]
set_location_assignment PIN_H3 -to cf_addr[8]
set_location_assignment PIN_K3 -to cf_addr[9]
set_location_assignment PIN_M7 -to cf_addr[10]
set_location_assignment PIN_K7 -to cf_atasel
set_location_assignment PIN_J2 -to cf_cs_n[0]
set_location_assignment PIN_K8 -to cf_cs_n[1]
set_location_assignment PIN_N3 -to cf_data[0]
set_location_assignment PIN_L2 -to cf_data[1]
set_location_assignment PIN_N8 -to cf_data[2]
set_location_assignment PIN_M4 -to cf_data[3]
set_location_assignment PIN_N6 -to cf_data[4]
set_location_assignment PIN_N1 -to cf_data[5]
set_location_assignment PIN_N9 -to cf_data[6]
set_location_assignment PIN_P3 -to cf_data[7]
set_location_assignment PIN_N10 -to cf_data[8]
set_location_assignment PIN_M2 -to cf_data[9]
set_location_assignment PIN_N5 -to cf_data[10]
set_location_assignment PIN_M3 -to cf_data[11]
set_location_assignment PIN_N7 -to cf_data[12]
set_location_assignment PIN_L1 -to cf_data[13]
set_location_assignment PIN_N4 -to cf_data[14]
set_location_assignment PIN_L3 -to cf_data[15]
set_location_assignment PIN_M9 -to cf_iord_n
set_location_assignment PIN_M10 -to cf_iowr_n
set_location_assignment PIN_H4 -to cf_power
set_location_assignment PIN_G2 -to cf_rfu
set_location_assignment PIN_L5 -to cf_we_n
set_location_assignment PIN_E15 -to pll_e0_out
set_location_assignment PIN_K17 -to clk 


# Assign unassign pin to to VIRTUAL PIN
# =====================================
set_instance_assignment -name VIRTUAL_PIN ON -to pll_c0_out
set_instance_assignment -name VIRTUAL_PIN ON -to pll_c0_domain
set_instance_assignment -name VIRTUAL_PIN ON -to pll_c0_domain_reset
set_instance_assignment -name VIRTUAL_PIN ON -to reset_to_the_lan91c111

# Setting pulled-up and pulled-to_ground values to certain pins
# ==============================================================
set_instance_assignment -name RESERVE_PIN "AS OUTPUT DRIVING GROUND" -to ENET_ADS_N
set_instance_assignment -name RESERVE_PIN "AS OUTPUT DRIVING GROUND" -to ENET_AEN


project_close
