# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "/data/sc-build/SN-linux/code/7.2-r/system_designs/example_designs/ExampleDesignMatrix/build/vhdl/niosII_stratix_1s10/standard/NiosII_stratix_1s10_standard.qpf"
set_global_assignment -name VHDL_FILE altera_europa_support.vhd
project_close