  //Example instantiation for system 'nios_system'
  nios_system nios_system_inst
    (
      .I2C_SCLK_from_the_AV_Config        (I2C_SCLK_from_the_AV_Config),
      .I2C_SDAT_to_and_from_the_AV_Config (I2C_SDAT_to_and_from_the_AV_Config),
      .KEY_to_the_Pushbuttons             (KEY_to_the_Pushbuttons),
      .LEDG_from_the_Green_LEDs           (LEDG_from_the_Green_LEDs),
      .LEDR_from_the_Red_LEDs             (LEDR_from_the_Red_LEDs),
      .SRAM_ADDR_from_the_SRAM            (SRAM_ADDR_from_the_SRAM),
      .SRAM_CE_N_from_the_SRAM            (SRAM_CE_N_from_the_SRAM),
      .SRAM_DQ_to_and_from_the_SRAM       (SRAM_DQ_to_and_from_the_SRAM),
      .SRAM_LB_N_from_the_SRAM            (SRAM_LB_N_from_the_SRAM),
      .SRAM_OE_N_from_the_SRAM            (SRAM_OE_N_from_the_SRAM),
      .SRAM_UB_N_from_the_SRAM            (SRAM_UB_N_from_the_SRAM),
      .SRAM_WE_N_from_the_SRAM            (SRAM_WE_N_from_the_SRAM),
      .SW_to_the_Slider_Switches          (SW_to_the_Slider_Switches),
      .UART_RXD_to_the_Serial_Port        (UART_RXD_to_the_Serial_Port),
      .UART_TXD_from_the_Serial_Port      (UART_TXD_from_the_Serial_Port),
      .VGA_BLANK_from_the_VGA_Controller  (VGA_BLANK_from_the_VGA_Controller),
      .VGA_B_from_the_VGA_Controller      (VGA_B_from_the_VGA_Controller),
      .VGA_CLK_from_the_VGA_Controller    (VGA_CLK_from_the_VGA_Controller),
      .VGA_G_from_the_VGA_Controller      (VGA_G_from_the_VGA_Controller),
      .VGA_HS_from_the_VGA_Controller     (VGA_HS_from_the_VGA_Controller),
      .VGA_R_from_the_VGA_Controller      (VGA_R_from_the_VGA_Controller),
      .VGA_SYNC_from_the_VGA_Controller   (VGA_SYNC_from_the_VGA_Controller),
      .VGA_VS_from_the_VGA_Controller     (VGA_VS_from_the_VGA_Controller),
      .audio_clk                          (audio_clk),
      .clk                                (clk),
      .clk_27                             (clk_27),
      .out_port_from_the_pio_0            (out_port_from_the_pio_0),
      .reset_n                            (reset_n),
      .sdram_clk                          (sdram_clk),
      .sys_clk                            (sys_clk),
      .vga_clk                            (vga_clk),
      .zs_addr_from_the_SDRAM             (zs_addr_from_the_SDRAM),
      .zs_ba_from_the_SDRAM               (zs_ba_from_the_SDRAM),
      .zs_cas_n_from_the_SDRAM            (zs_cas_n_from_the_SDRAM),
      .zs_cke_from_the_SDRAM              (zs_cke_from_the_SDRAM),
      .zs_cs_n_from_the_SDRAM             (zs_cs_n_from_the_SDRAM),
      .zs_dq_to_and_from_the_SDRAM        (zs_dq_to_and_from_the_SDRAM),
      .zs_dqm_from_the_SDRAM              (zs_dqm_from_the_SDRAM),
      .zs_ras_n_from_the_SDRAM            (zs_ras_n_from_the_SDRAM),
      .zs_we_n_from_the_SDRAM             (zs_we_n_from_the_SDRAM)
    );

