# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "U:/Examples/NiosII_Computer_Systems/DE2/DE2_Media_Computer/verilog/DE2_Media_Computer.qpf"
project_close