onerr {resume}
add list -bin /test_bench/clk
add list -hex /test_bench/DUT/the_cpu_0/i_readdata
add list -hex /test_bench/DUT/the_cpu_0/i_readdatavalid
add list -hex /test_bench/DUT/the_cpu_0/i_waitrequest
add list -hex /test_bench/DUT/the_cpu_0/i_address
add list -hex /test_bench/DUT/the_cpu_0/i_read
add list -hex /test_bench/DUT/the_cpu_0/clk
add list -hex /test_bench/DUT/the_cpu_0/reset_n
add list -hex /test_bench/DUT/the_cpu_0/d_readdata
add list -hex /test_bench/DUT/the_cpu_0/d_waitrequest
add list -hex /test_bench/DUT/the_cpu_0/d_irq
add list -hex /test_bench/DUT/the_cpu_0/d_address
add list -hex /test_bench/DUT/the_cpu_0/d_byteenable
add list -hex /test_bench/DUT/the_cpu_0/d_read
add list -hex /test_bench/DUT/the_cpu_0/d_write
add list -hex /test_bench/DUT/the_cpu_0/d_writedata
add list -hex /test_bench/DUT/the_cpu_0/the_cpu_0_test_bench/W_pcb
add list -asc /test_bench/DUT/the_cpu_0/the_cpu_0_test_bench/W_vinst
add list -hex /test_bench/DUT/the_cpu_0/the_cpu_0_test_bench/W_valid
add list -hex /test_bench/DUT/the_cpu_0/the_cpu_0_test_bench/W_iw
add list -hex /test_bench/DUT/the_cpu_1/i_readdata
add list -hex /test_bench/DUT/the_cpu_1/i_readdatavalid
add list -hex /test_bench/DUT/the_cpu_1/i_waitrequest
add list -hex /test_bench/DUT/the_cpu_1/i_address
add list -hex /test_bench/DUT/the_cpu_1/i_read
add list -hex /test_bench/DUT/the_cpu_1/clk
add list -hex /test_bench/DUT/the_cpu_1/reset_n
add list -hex /test_bench/DUT/the_cpu_1/d_readdata
add list -hex /test_bench/DUT/the_cpu_1/d_waitrequest
add list -hex /test_bench/DUT/the_cpu_1/d_irq
add list -hex /test_bench/DUT/the_cpu_1/d_address
add list -hex /test_bench/DUT/the_cpu_1/d_byteenable
add list -hex /test_bench/DUT/the_cpu_1/d_read
add list -hex /test_bench/DUT/the_cpu_1/d_write
add list -hex /test_bench/DUT/the_cpu_1/d_writedata
add list -hex /test_bench/DUT/the_cpu_1/the_cpu_1_test_bench/W_pcb
add list -asc /test_bench/DUT/the_cpu_1/the_cpu_1_test_bench/W_vinst
add list -hex /test_bench/DUT/the_cpu_1/the_cpu_1_test_bench/W_valid
add list -hex /test_bench/DUT/the_cpu_1/the_cpu_1_test_bench/W_iw
add list -bin /test_bench/DUT/the_onchip_memory_0/chipselect
add list -bin /test_bench/DUT/the_onchip_memory_0/write
add list -hex /test_bench/DUT/the_onchip_memory_0/address
add list -bin /test_bench/DUT/the_onchip_memory_0/byteenable
add list -hex /test_bench/DUT/the_onchip_memory_0/readdata
add list -hex /test_bench/DUT/the_onchip_memory_0/writedata
add list -bin /test_bench/DUT/the_onchip_memory_1/chipselect
add list -bin /test_bench/DUT/the_onchip_memory_1/write
add list -hex /test_bench/DUT/the_onchip_memory_1/address
add list -bin /test_bench/DUT/the_onchip_memory_1/byteenable
add list -hex /test_bench/DUT/the_onchip_memory_1/readdata
add list -hex /test_bench/DUT/the_onchip_memory_1/writedata
add list -bin /test_bench/DUT/the_onchip_memory_2/chipselect
add list -bin /test_bench/DUT/the_onchip_memory_2/write
add list -hex /test_bench/DUT/the_onchip_memory_2/address
add list -bin /test_bench/DUT/the_onchip_memory_2/byteenable
add list -hex /test_bench/DUT/the_onchip_memory_2/readdata
add list -hex /test_bench/DUT/the_onchip_memory_2/writedata
add list -bin /test_bench/DUT/the_mutex_0/chipselect
add list -hex /test_bench/DUT/the_mutex_0/address
add list -bin /test_bench/DUT/the_mutex_0/write
add list -hex /test_bench/DUT/the_mutex_0/data_from_cpu
add list -bin /test_bench/DUT/the_mutex_0/read
add list -hex /test_bench/DUT/the_mutex_0/data_to_cpu
add list -hex /test_bench/DUT/the_mutex_0/reset_reg
add list -hex /test_bench/DUT/the_mutex_0/mutex_state
add list -hex /test_bench/DUT/the_mutex_0/mutex_value
add list -hex /test_bench/DUT/the_mutex_0/mutex_owner
configure list -usestrobe 0
configure list -strobestart {0 ps} -strobeperiod {0 ps}
configure list -delta none
configure list -usegating 1
configure list -gateexpr { /test_bench/clk'rising }